# Generated by Django 4.2.10 on 2024-03-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("desc", models.TextField(blank=True)),
                ("release_date", models.DateTimeField()),
                ("actors", models.CharField(max_length=500)),
                ("youtube_link", models.TextField(blank=True)),
                ("poster", models.ImageField(blank=True, upload_to="Galary")),
            ],
        ),
    ]
