# Generated by Django 4.2.10 on 2024-03-03 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Movie_app", "0002_alter_movie_data_poster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie_data",
            name="slug",
        ),
    ]
