# Generated by Django 4.2.10 on 2024-03-05 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Movie_app", "0004_movie_data_added_by_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("rating", models.FloatField(blank=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Movie_app.movie_data",
                    ),
                ),
            ],
        ),
    ]
