# Generated by Django 4.2.10 on 2024-03-05 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Movie_app", "0005_userreviews"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userreviews",
            old_name="review",
            new_name="review_id",
        ),
    ]
