# Generated by Django 4.2.10 on 2024-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Movie_app", "0006_rename_review_userreviews_review_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreviews",
            name="review_id",
            field=models.IntegerField(),
        ),
    ]
