# Generated by Django 4.2.10 on 2024-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Movie_app", "0007_alter_userreviews_review_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreviews",
            name="rating",
            field=models.FloatField(null=True),
        ),
    ]
