# Generated by Django 4.2.10 on 2024-03-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Movie_app", "0008_alter_userreviews_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie_data",
            name="category",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
